### ISSUE TITLE
Misssing documentation

### ISSUE THREAD

**Issue by hoschwenk** [tommccoy1/hans#1]

**Comment by hoschwenk** [comment]
This works seems to be very interesting and I would like to evaluate other NLI system on the HANS corpus. Could you please provide some documentation how to use the code ?
In particular how to create the same corpus that was used in your paper https://arxiv.org/pdf/1902.01007.pdf

**Comment by hoschwenk** [comment]
I guess that we just use the file heuristics_evaluation_set.txt ?

**Comment by tommccoy1** [comment]
Thank you for the interest! I have updated the README with instructions for use; let me know if anything else remains unclear.
