### ISSUE TITLE
Meaning of some abbreviations

### ISSUE THREAD

**Issue by cemilcengiz** [tommccoy1/hans#5]
Hi, can you please share the meaning of some abbreviations used as subcategories. In particular, what do "NP/S" and "NP/Z" mean? Thank you in advance.

**Comment by tommccoy1** [comment]
Yes, those two abbreviations are taken from the psycholinguistics literature. Both NP/S and NP/Z sentences are sentences that are temporarily ambiguous as you read the sentence from left to right, but then the ambiguity is resolved once you have finished the sentence.

In an NP/S sentence, the ambiguity is that it's unclear if the object of the verb is a noun phrase (NP) or sentence (S), hence the name NP/S. An example is "Alice believes Mary is lying." When you have only heard the start of the sentence ("Alice believes Mary"), it is possible for the verb "believed" to take an NP (if the sentence stops there), or a sentence (if it continues as "Alice believes Mary is lying.") 

In an NP/Z sentence, the ambiguity is whether the object is a noun phrase (NP) or if there is no object (Z, for "zero"), hence the name NP/Z. An example is "While the children played the violin gathered dust in the attic" (interpreted as "While the children played [a game], the violin gathered dust in the attic.") When people have only heard the start of the sentence "While the children played the violin", they often assume that "the violin" is the object of "played" (the NP reading), but then once you've heard the whole sentence you realize that actually "played" has no direct object (the Z reading).

Both types of sentences have been used in psycholinguistics research about how humans process garden path sentences.
